-- V1: Initial schema baseline
-- Captures the existing schema created by Hibernate prior to Flyway adoption.

CREATE TABLE users (
                       id         BIGINT       NOT NULL,
                       email      VARCHAR(255) NOT NULL,
                       password   VARCHAR(255) NOT NULL,
                       created_at TIMESTAMP(6) NOT NULL,
                       updated_at TIMESTAMP(6) NOT NULL
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE users ADD CONSTRAINT users_pkey PRIMARY KEY (id);
ALTER TABLE users ADD CONSTRAINT users_email_key UNIQUE (email);

CREATE TABLE cv (
                    id         BIGINT       NOT NULL,
                    user_id    BIGINT       NOT NULL,
                    cv_name    VARCHAR(100) NOT NULL,
                    content    TEXT,
                    created_at TIMESTAMP(6) NOT NULL,
                    updated_at TIMESTAMP(6) NOT NULL,
                    deleted_at TIMESTAMP(6)
);

ALTER TABLE cv ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE cv ADD CONSTRAINT cv_pkey PRIMARY KEY (id);
CREATE UNIQUE INDEX uq_cv_user_name_active ON cv (user_id, cv_name) WHERE (deleted_at IS NULL);

CREATE TABLE jobs (
                      id              BIGINT       NOT NULL,
                      user_id         BIGINT       NOT NULL,
                      job_title       VARCHAR(200) NOT NULL,
                      company         VARCHAR(200) NOT NULL,
                      job_description TEXT,
                      job_url         VARCHAR(500),
                      notes           TEXT,
                      status          VARCHAR(20)  NOT NULL,
                      applied_at      TIMESTAMP(6),
                      created_at      TIMESTAMP(6) NOT NULL,
                      updated_at      TIMESTAMP(6) NOT NULL,
                      deleted_at      TIMESTAMP(6),
                      CONSTRAINT jobs_status_check CHECK (
                          status IN ('SAVED', 'APPLIED', 'INTERVIEWING', 'OFFERED', 'REJECTED', 'DECLINED', 'ARCHIVED')
                          )
);

ALTER TABLE jobs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE jobs ADD CONSTRAINT jobs_pkey PRIMARY KEY (id);
CREATE INDEX idx_job_user_id ON jobs (user_id);
CREATE INDEX idx_job_user_status ON jobs (user_id, status);

CREATE TABLE analyses (
                          id                  BIGINT  NOT NULL,
                          user_id             BIGINT  NOT NULL,
                          cv_id               BIGINT  NOT NULL,
                          job_id              BIGINT  NOT NULL,
                          match_score         INTEGER NOT NULL,
                          matched_skills      TEXT,
                          missing_skills      TEXT,
                          actionable_feedback TEXT,
                          created_at          TIMESTAMP(6) NOT NULL,
                          deleted_at          TIMESTAMP(6)
);

ALTER TABLE analyses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE analyses ADD CONSTRAINT analyses_pkey PRIMARY KEY (id);
CREATE INDEX idx_analysis_cv_id ON analyses (cv_id);
CREATE INDEX idx_analysis_job_id ON analyses (job_id);