-- V6: Add audit_logs table
-- Append-only record of security-relevant events. Rows are never updated or
-- deleted. No foreign key on user_id: an audit entry must survive deletion of
-- the account it refers to, and may reference an email that never existed.

CREATE TABLE audit_logs (
    id         BIGINT       NOT NULL,
    action     VARCHAR(30)  NOT NULL,
    user_id    BIGINT,
    email      VARCHAR(255) NOT NULL,
    ip_address VARCHAR(45),
    created_at TIMESTAMP(6) NOT NULL
);

ALTER TABLE audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_pkey PRIMARY KEY (id);

CREATE INDEX idx_audit_log_email ON audit_logs (email);
CREATE INDEX idx_audit_log_action ON audit_logs (action);
CREATE INDEX idx_audit_log_created_at ON audit_logs (created_at);